# DSN (Data Source Name) examples
#
# sqlite3:
#   sqlite3://<%= root %>/db/development.sqlite3
# mysql:
#   mysql://user:pass@host/database
# postgres:
#   postgres://user:pass@host/database
# heroku:
#   <%= ENV['DATABASE_URL'] %>
production:
  dsn: <%= ENV['DATABASE_URL'] %>
development:
  dsn: sqlite3://<%= File.expand_path(File.dirname(__FILE__)) %>/development.sqlite3
test:
  dsn: sqlite3://<%= File.expand_path(File.dirname(__FILE__)) %>/test.sqlite3
